unique_ids:
  assets:
    standard-page.html: 35RKDPQ4S7KY3KXH4IVSZYNSJUEKGW36
    theme.css: KVPI7TVTEHKLA3KFURDZFR37DE52R5JG
  forms:
    Form1: B6O72VCVVIUHROH663WBQTMOXVAJ6JAC
  modules: {}
  scripts: {}
  server_modules: {}
